
name: Bug Report
description: File a bug report
title: ""
labels: ["PR", "VeronteApp","Software"]
assignees:
  - jmt1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description of the problem
      description: Enter the problem found
      placeholder: I found problem with...
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 6.7
        - 6.8
        - 6.9
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: data
    attributes:
      label: Drag zip, image and video
      description: Drag the downloaded zip, image and video
