name: Bug Report VerontePDITuning
description: File a bug report
title: "VerontePDITuning Bug"
labels: ["PR", "VerontePDITuning", "Software"]
assignees:
  - jmt1
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the problem
      description: Enter the problem found
      placeholder: I found problem with...
    validations:
      required: false
  - type: textarea
    id: data
    attributes:
      label: Drag the downloaded zip, image and video
